# Generated by Django 3.1.2 on 2022-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='text',
        ),
    ]
